name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # setiap hari jam 00:00 UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg  
            dist/github-snake-dark.svg?palette=github-dark

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: snake-graph
          path: ./dist

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
